import type { AppState } from '../types'

export interface XMLResult {
  xml: string
  valid: boolean
  errors: string[]
}

/**
 * Generate ITR-3 XML conforming to AY 2026-27 schema.
 * All generation is client-side — no server involved.
 */
export function generateITR3XML(state: AppState): XMLResult {
  const { tax, schedules, parsed } = state
  const errors: string[] = []

  if (!tax || !schedules) {
    return { xml: '', valid: false, errors: ['No tax computation available — parse documents first'] }
  }

  const form16 = parsed.form16
  const pan = form16?.pan ?? ''

  // Validation checks
  if (!pan) errors.push('PAN not found in Form 16 — required for XML filing')
  if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) errors.push(`PAN format invalid: ${pan}`)
  if (schedules.S.grossSalary === 0 && !parsed.broker && !parsed.mfStatement)
    errors.push('No income data found — verify parsed documents')

  if (errors.length > 0) {
    return { xml: '', valid: false, errors }
  }

  const s = schedules.S
  const bp = schedules.BP
  const cg = schedules.CG
  const os = schedules.OS
  const cyla = schedules.CYLA
  const cfl = schedules.CFL

  const n = (v: number) => Math.round(v).toString()
  const tan = form16?.tanEmployer ?? ''
  const employerName = form16?.employerName ?? ''

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ITR-3 AY 2026-27 — Generated by ITR Filing Utility v1.0 -->
<!-- IMPORTANT: Review all values on incometax.gov.in before submission -->
<ITR>
  <ITR3>
    <PersonalInfo>
      <PAN>${pan}</PAN>
      <AssessmentYear>2026-27</AssessmentYear>
      <FilingDate>${new Date().toISOString().split('T')[0]}</FilingDate>
    </PersonalInfo>

    <FilingStatus>
      <ReturnFileSec>11</ReturnFileSec>
      <NewTaxRegime>Y</NewTaxRegime>
      <EmployerCategory>OTH</EmployerCategory>
    </FilingStatus>

    <ScheduleS>
      <TotIncUnderHeadSalaries>${n(s.netTaxableSalary)}</TotIncUnderHeadSalaries>
      <Salaries>
        <NameOfEmployer>${escapeXML(employerName)}</NameOfEmployer>
        <TANofEmployer>${tan}</TANofEmployer>
        <GrossSalary>${n(s.grossSalary)}</GrossSalary>
        <ProfessionalTaxUS16iii>${n(s.professionalTax)}</ProfessionalTaxUS16iii>
        <StandardDeductionUS16ia>${n(s.standardDeduction)}</StandardDeductionUS16ia>
        <NetSalary>${n(s.netTaxableSalary)}</NetSalary>
      </Salaries>
    </ScheduleS>

    <ScheduleBP>
      <SpeculativeIncome>
        <Receipts>${n(bp.speculativeTurnover)}</Receipts>
        <ProfitFromSpeculativeActivity>${n(Math.max(0, bp.netSpeculativePnL))}</ProfitFromSpeculativeActivity>
        <LossFromSpeculativeActivity>${n(Math.max(0, -bp.netSpeculativePnL))}</LossFromSpeculativeActivity>
      </SpeculativeIncome>
    </ScheduleBP>

    <ScheduleCG>
      <Schedule111A>
        <ShortTermCGDTAARate>
          <STCGInc>${n(cg.netSTCG)}</STCGInc>
        </ShortTermCGDTAARate>
      </Schedule111A>
      <Schedule112A>
        <LongTermCGDTAARate>
          <LTCGInc>${n(cg.grossLTCG)}</LTCGInc>
          <LTCGIncGovtSec>0</LTCGIncGovtSec>
          <ExemptionUS112A>${n(cg.ltcgExemption)}</ExemptionUS112A>
          <TaxableLTCG>${n(cg.taxableLTCG)}</TaxableLTCG>
        </LongTermCGDTAARate>
      </Schedule112A>
      <TotalSTCG>${n(cg.netSTCG)}</TotalSTCG>
      <TotalLTCG>${n(cg.taxableLTCG)}</TotalLTCG>
    </ScheduleCG>

    <ScheduleOS>
      <IncFrmOthSrces>
        <DividendIncome>${n(os.dividendIncome)}</DividendIncome>
        <InterestIncome>${n(os.interestIncome)}</InterestIncome>
        <TotOthSrcExclSec>${n(os.total)}</TotOthSrcExclSec>
      </IncFrmOthSrces>
    </ScheduleOS>

    <ScheduleCYLA>
      <SalaryIncome>${n(cyla.netSalaryIncome)}</SalaryIncome>
      <HPLoss>0</HPLoss>
      <SpeculativeIncome>${n(cyla.netIntradayIncome)}</SpeculativeIncome>
      <STCGIncome>${n(cyla.netSTCG)}</STCGIncome>
      <LTCGIncome>${n(cyla.netLTCG)}</LTCGIncome>
      <OtherSources>${n(cyla.netOtherSources)}</OtherSources>
    </ScheduleCYLA>

    <ScheduleCFL>
      <CurrentYearLoss>
        <SpeculativeLoss>${n(cfl.intradayLossCarryForward)}</SpeculativeLoss>
        <STCLoss>${n(cfl.stclCarryForward)}</STCLoss>
        <LTCLoss>${n(cfl.ltclCarryForward)}</LTCLoss>
      </CurrentYearLoss>
    </ScheduleCFL>

    <ScheduleTaxPaid>
      <TDS1>
        <TaxDeductedAtSource>
          <TDSEmployer>
            <EmployerOrDeductorOrCollectPersonTAN>${tan}</EmployerOrDeductorOrCollectPersonTAN>
            <EmployerOrDeductorOrCollecterName>${escapeXML(employerName)}</EmployerOrDeductorOrCollecterName>
            <AmtForTaxDeduct>${n(s.grossSalary)}</AmtForTaxDeduct>
            <ClaimOutOfTotTDSOnSals>${n(tax.tdsDeducted)}</ClaimOutOfTotTDSOnSals>
          </TDSEmployer>
        </TaxDeductedAtSource>
      </TDS1>
    </ScheduleTaxPaid>

    <TaxComputation>
      <TotalIncome>${n(tax.totalIncome)}</TotalIncome>
      <SlabTaxableIncome>${n(tax.slabTaxableIncome)}</SlabTaxableIncome>
      <TaxOnSlabIncome>${n(tax.slabTax)}</TaxOnSlabIncome>
      <TaxOnSTCG>${n(tax.stcgTax)}</TaxOnSTCG>
      <TaxOnLTCG>${n(tax.ltcgTax)}</TaxOnLTCG>
      <Surcharge>${n(tax.surcharge)}</Surcharge>
      <HealthAndEduCess>${n(tax.cess)}</HealthAndEduCess>
      <TotalTaxPayable>${n(tax.totalTaxPayable)}</TotalTaxPayable>
      <TDSDeducted>${n(tax.tdsDeducted)}</TDSDeducted>
      <AdvanceTaxPaid>${n(tax.advanceTaxPaid)}</AdvanceTaxPaid>
      <NetTaxPayable>${n(Math.max(0, tax.netPayable))}</NetTaxPayable>
      <Refund>${n(Math.max(0, -tax.netPayable))}</Refund>
    </TaxComputation>

  </ITR3>
</ITR>`

  // Basic structural validation
  const structErrors = validateXMLStructure(xml, pan, tax.netPayable)
  if (structErrors.length > 0) {
    return { xml, valid: false, errors: structErrors }
  }

  return { xml, valid: true, errors: [] }
}

function escapeXML(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function validateXMLStructure(xml: string, pan: string, netPayable: number): string[] {
  const errors: string[] = []

  // Required tags present
  const required = ['<PAN>', '<AssessmentYear>', '<NewTaxRegime>', '<TotalTaxPayable>']
  for (const tag of required) {
    if (!xml.includes(tag)) errors.push(`Missing required XML element: ${tag}`)
  }

  // PAN format
  if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) {
    errors.push(`PAN ${pan} does not match required format AAAAA0000A`)
  }

  // Net payable consistency
  const netMatch = xml.match(/<NetTaxPayable>(\d+)<\/NetTaxPayable>/)
  if (netMatch) {
    const xmlNet = parseInt(netMatch[1])
    const expected = Math.max(0, Math.round(netPayable))
    if (Math.abs(xmlNet - expected) > 1) {
      errors.push(`NetTaxPayable mismatch: XML has ${xmlNet}, expected ${expected}`)
    }
  }

  return errors
}
