import type { AppState } from '../types'

export interface XMLResult {
  xml: string
  valid: boolean
  errors: string[]
}

/**
 * Generate ITR-3 XML conforming to AY 2026-27 schema.
 * All generation is client-side — no server involved.
 */
export function generateITR3XML(state: AppState): XMLResult {
  const { tax, schedules, parsed } = state
  const errors: string[] = []

  if (!tax || !schedules) {
    return { xml: '', valid: false, errors: ['No tax computation available — parse documents first'] }
  }

  const form16 = parsed.form16
  const pan = form16?.pan ?? ''

  // Validation checks
  if (!pan) errors.push('PAN not found in Form 16 — required for XML filing')
  if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) errors.push(`PAN format invalid: ${pan}`)
  if (schedules.S.grossSalary === 0 && !parsed.broker && !parsed.mfStatement)
    errors.push('No income data found — verify parsed documents')

  if (errors.length > 0) {
    return { xml: '', valid: false, errors }
  }

  const s = schedules.S
  const bp = schedules.BP
  const cg = schedules.CG
  const os = schedules.OS
  const cyla = schedules.CYLA
  const cfl = schedules.CFL

  const n = (v: number) => Math.round(v).toString()
  const tan = form16?.tanEmployer ?? ''
  const employerName = form16?.employerName ?? ''

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ITR-3 AY 2026-27 — Generated by ITR Filing Utility v1.0 -->
<!-- IMPORTANT: Review all values on incometax.gov.in before submission -->
<ITR>
  <ITR3>
    <PersonalInfo>
      <PAN>${pan}</PAN>
      <AssessmentYear>2026-27</AssessmentYear>
      <FilingDate>${new Date().toISOString().split('T')[0]}</FilingDate>
    </PersonalInfo>

    <FilingStatus>
      <ReturnFileSec>11</ReturnFileSec>
      <NewTaxRegime>Y</NewTaxRegime>
      <EmployerCategory>OTH</EmployerCategory>
    </FilingStatus>

    <ScheduleS>
      <TotIncUnderHeadSalaries>${n(s.netTaxableSalary)}</TotIncUnderHeadSalaries>
      <Salaries>
        <NameOfEmployer>${escapeXML(employerName)}</NameOfEmployer>
        <TANofEmployer>${tan}</TANofEmployer>
        <GrossSalary>${n(s.grossSalary)}</GrossSalary>
        <ProfessionalTaxUS16iii>${n(s.professionalTax)}</ProfessionalTaxUS16iii>
        <StandardDeductionUS16ia>${n(s.standardDeduction)}</StandardDeductionUS16ia>
        <NetSalary>${n(s.netTaxableSalary)}</NetSalary>
      </Salaries>
    </ScheduleS>

    <ScheduleBP>
      <SpeculativeIncome>
        <Receipts>${n(bp.speculativeTurnover)}</Receipts>
        <ProfitFromSpeculativeActivity>${n(Math.max(0, bp.netSpeculativePnL))}</ProfitFromSpeculativeActivity>
        <LossFromSpeculativeActivity>${n(Math.max(0, -bp.netSpeculativePnL))}</LossFromSpeculativeActivity>
      </SpeculativeIncome>
    </ScheduleBP>

    <ScheduleCG>
      <Schedule111A>
        <ShortTermCGDTAARate>
          <STCGInc>${n(cg.netSTCG)}</STCGInc>
        </ShortTermCGDTAARate>
      </Schedule111A>
      <Schedule112A>
        <LongTermCGDTAARate>
          <LTCGInc>${n(cg.grossLTCG)}</LTCGInc>
          <LTCGIncGovtSec>0</LTCGIncGovtSec>
          <ExemptionUS112A>${n(cg.ltcgExemption)}</ExemptionUS112A>
          <TaxableLTCG>${n(cg.taxableLTCG)}</TaxableLTCG>
        </LongTermCGDTAARate>
      </Schedule112A>
      <TotalSTCG>${n(cg.netSTCG)}</TotalSTCG>
      <TotalLTCG>${n(cg.taxableLTCG)}</TotalLTCG>
    </ScheduleCG>

    <ScheduleOS>
      <IncFrmOthSrces>
        <DividendIncome>${n(os.dividendIncome)}</DividendIncome>
        <InterestIncome>${n(os.interestIncome)}</InterestIncome>
        <TotOthSrcExclSec>${n(os.total)}</TotOthSrcExclSec>
      </IncFrmOthSrces>
    </ScheduleOS>

    <ScheduleCYLA>
      <SalaryIncome>${n(cyla.netSalaryIncome)}</SalaryIncome>
      <HPLoss>0</HPLoss>
      <SpeculativeIncome>${n(cyla.netIntradayIncome)}</SpeculativeIncome>
      <STCGIncome>${n(cyla.netSTCG)}</STCGIncome>
      <LTCGIncome>${n(cyla.netLTCG)}</LTCGIncome>
      <OtherSources>${n(cyla.netOtherSources)}</OtherSources>
    </ScheduleCYLA>

    <ScheduleCFL>
      <CurrentYearLoss>
        <SpeculativeLoss>${n(cfl.intradayLossCarryForward)}</SpeculativeLoss>
        <STCLoss>${n(cfl.stclCarryForward)}</STCLoss>
        <LTCLoss>${n(cfl.ltclCarryForward)}</LTCLoss>
      </CurrentYearLoss>
    </ScheduleCFL>

    <ScheduleTaxPaid>
      <TDS1>
        <TaxDeductedAtSource>
          <TDSEmployer>
            <EmployerOrDeductorOrCollectPersonTAN>${tan}</EmployerOrDeductorOrCollectPersonTAN>
            <EmployerOrDeductorOrCollecterName>${escapeXML(employerName)}</EmployerOrDeductorOrCollecterName>
            <AmtForTaxDeduct>${n(s.grossSalary)}</AmtForTaxDeduct>
            <ClaimOutOfTotTDSOnSals>${n(tax.tdsDeducted)}</ClaimOutOfTotTDSOnSals>
          </TDSEmployer>
        </TaxDeductedAtSource>
      </TDS1>
    </ScheduleTaxPaid>

    <TaxComputation>
      <TotalIncome>${n(tax.totalIncome)}</TotalIncome>
      <SlabTaxableIncome>${n(tax.slabTaxableIncome)}</SlabTaxableIncome>
      <TaxOnSlabIncome>${n(tax.slabTax)}</TaxOnSlabIncome>
      <TaxOnSTCG>${n(tax.stcgTax)}</TaxOnSTCG>
      <TaxOnLTCG>${n(tax.ltcgTax)}</TaxOnLTCG>
      <Surcharge>${n(tax.surcharge)}</Surcharge>
      <HealthAndEduCess>${n(tax.cess)}</HealthAndEduCess>
      <TotalTaxPayable>${n(tax.totalTaxPayable)}</TotalTaxPayable>
      <TDSDeducted>${n(tax.tdsDeducted)}</TDSDeducted>
      <AdvanceTaxPaid>${n(tax.advanceTaxPaid)}</AdvanceTaxPaid>
      <NetTaxPayable>${n(Math.max(0, tax.netPayable))}</NetTaxPayable>
      <Refund>${n(Math.max(0, -tax.netPayable))}</Refund>
    </TaxComputation>

  </ITR3>
</ITR>`

  // Basic structural validation
  const structErrors = validateXMLStructure(xml, pan, tax.netPayable)
  if (structErrors.length > 0) {
    return { xml, valid: false, errors: structErrors }
  }

  return { xml, valid: true, errors: [] }
}

function escapeXML(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function validateXMLStructure(xml: string, pan: string, netPayable: number): string[] {
  const errors: string[] = []

  // Required tags present
  const required = ['<PAN>', '<AssessmentYear>', '<NewTaxRegime>', '<TotalTaxPayable>']
  for (const tag of required) {
    if (!xml.includes(tag)) errors.push(`Missing required XML element: ${tag}`)
  }

  // PAN format
  if (pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan)) {
    errors.push(`PAN ${pan} does not match required format AAAAA0000A`)
  }

  // Net payable consistency
  const netMatch = xml.match(/<NetTaxPayable>(\d+)<\/NetTaxPayable>/)
  if (netMatch) {
    const xmlNet = parseInt(netMatch[1])
    const expected = Math.max(0, Math.round(netPayable))
    if (Math.abs(xmlNet - expected) > 1) {
      errors.push(`NetTaxPayable mismatch: XML has ${xmlNet}, expected ${expected}`)
    }
  }

  return errors
}

// ─── XML v2 Router — multi-form support ──────────────────────────────────────

/**
 * generateXML_v2 — routes to correct ITR form generator based on state.selectedITRForm.
 * Also injects BankAccountDetails and ScheduleHP/AL nodes for v2.
 */
export function generateXML_v2(state: AppState): XMLResult {
  const form = state.selectedITRForm ?? 'ITR3'

  // Bank account validation gate
  if (state.bankAccounts.length === 0) {
    return { xml: '', valid: false, errors: ['Add at least one bank account before downloading XML.'] }
  }
  if (!state.bankAccounts.some(a => a.isRefundAccount)) {
    return { xml: '', valid: false, errors: ['Mark one bank account as refund account before downloading XML.'] }
  }

  // Schedule AL gate
  const needsAL = (state.tax?.totalIncome ?? 0) > 5_000_000 && form !== 'ITR1' && form !== 'ITR4'
  if (needsAL && !state.scheduleAL) {
    return { xml: '', valid: false, errors: ['Schedule AL is required for income above ₹50L. Complete it before downloading XML.'] }
  }

  // Generate base ITR-3 XML then add v2 sections
  const base = generateITR3XML(state)
  if (!base.valid) return base

  // Inject v2 nodes into the XML
  const bankXML = generateBankAccountsXML(state)
  const hpXML   = generateScheduleHPXML(state)
  const alXML   = needsAL && state.scheduleAL ? generateScheduleALXML(state.scheduleAL) : ''

  // Inject before closing </ITR3> tag
  const injected = base.xml.replace(
    '</ITR3>',
    `${hpXML}${alXML}${bankXML}\n  </ITR3>`
  )

  const formComment = injected.replace(
    '<!-- ITR-3 AY 2026-27',
    `<!-- ${form} AY 2026-27`
  )

  return { xml: formComment, valid: true, errors: [] }
}

function generateBankAccountsXML(state: AppState): string {
  const accounts = state.bankAccounts
  const rows = accounts.map((a, i) => `
    <BankAccount>
      <SlNo>${i + 1}</SlNo>
      <IFSCCode>${esc(a.ifscCode)}</IFSCCode>
      <BankName>${esc(a.bankName)}</BankName>
      <AccountNo>${esc(a.accountNumber)}</AccountNo>
      <AccountType>${a.accountType === 'savings' ? 'SB' : a.accountType === 'current' ? 'CA' : 'CC'}</AccountType>
      <RefundAccount>${a.isRefundAccount ? 'Y' : 'N'}</RefundAccount>
    </BankAccount>`).join('')

  return `\n  <BankAccountDetails>${rows}\n  </BankAccountDetails>`
}

function generateScheduleHPXML(state: AppState): string {
  const hp = state.schedules_v2?.HP
  if (!hp?.properties?.length) return ''

  const rows = hp.properties.map((p: any, i: number) => `
    <HP${i + 1}>
      <PropertyType>${p.propertyType === 'self_occupied' ? 'SOP' : p.propertyType === 'let_out' ? 'LOP' : 'DLOP'}</PropertyType>
      <GrossAnnualRent>${n(p.annualRentReceived)}</GrossAnnualRent>
      <MunicipalTax>${n(p.municipalTaxPaid)}</MunicipalTax>
      <NetAnnualValue>${n(p.netAnnualValue)}</NetAnnualValue>
      <StandardDeduction>${n(p.standardDeduction30pct)}</StandardDeduction>
      <InterestPayable>${n(p.interestOnLoan)}</InterestPayable>
      <IncomeFromHP>${n(p.incomeFromHP)}</IncomeFromHP>
    </HP${i + 1}>`).join('')

  return `\n  <ScheduleHP>${rows}\n  </ScheduleHP>`
}

function generateScheduleALXML(al: NonNullable<AppState['scheduleAL']>): string {
  const immovableRows = al.immovableAssets.map((a, i) => `
      <LandBuilding>
        <SLNo>${i + 1}</SLNo>
        <Description>${esc(a.description)}</Description>
        <AssetType>${a.assetType}</AssetType>
        <CostAcquisition>${n(a.costOfAcquisition)}</CostAcquisition>
      </LandBuilding>`).join('')

  return `
  <ScheduleAL>
    <ImmovableAssets>${immovableRows}
    </ImmovableAssets>
    <MovableAssets>
      <CashInHand>${n(al.cashInHand)}</CashInHand>
      <Deposits>${n(al.deposits)}</Deposits>
      <SharesSecurities>${n(al.sharesDebentures)}</SharesSecurities>
      <InsurancePolicies>${n(al.insurancePolicies)}</InsurancePolicies>
      <LoansAdvancesGiven>${n(al.loansAdvances)}</LoansAdvancesGiven>
      <MotorVehicles>${n(al.motorVehicles)}</MotorVehicles>
      <JewelleryBullion>${n(al.jewellery)}</JewelleryBullion>
      <ArchaeologicalCollections>${n(al.archaeologicalArt)}</ArchaeologicalCollections>
      <OtherAssets>${n(al.otherAssets)}</OtherAssets>
    </MovableAssets>
    <Liabilities>
      <LiabilityImmovable>${n(al.liabilityImmovable)}</LiabilityImmovable>
      <LiabilityOther>${n(al.liabilityOther)}</LiabilityOther>
    </Liabilities>
    <TotalAssets>${n(al.totalAssets)}</TotalAssets>
    <TotalLiabilities>${n(al.totalLiabilities)}</TotalLiabilities>
  </ScheduleAL>`
}

function n(v: number): string { return Math.round(v).toString() }
function esc(s: string): string { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') }
